In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


a=pd.read_csv(r"/Users/vijay/Downloads/nlp-getting-started/train.csv")
a

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [2]:
a=a[['text','target']]
a

text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
...                                                 ...     ...
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [3]:
data=np.array(a)[:,0]
data

array(['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all',
       'Forest fire near La Ronge Sask. Canada',
       "All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected",
       ...,
       'M1.94 [01:04 UTC]?5km S of Volcano Hawaii. http://t.co/zDtoyd8EbJ',
       'Police investigating after an e-bike collided with a car in Little Portugal. E-bike rider suffered serious non-life threatening injuries.',
       'The Latest: More Homes Razed by Northern California Wildfire - ABC News http://t.co/YmY4rSkQ3d'],
      dtype=object)

In [4]:
y=np.array(a)[:,1]
y=y.astype('int')
y


array([1, 1, 1, ..., 1, 1, 1])

In [5]:
from sklearn.feature_extraction.text import CountVectorizer 
vect = CountVectorizer()
vect.fit(data)
X = vect.transform(data) 

feature_names = vect.get_feature_names()
print("Number of features: {}".format(len(feature_names)))
print("First 100 features:\n{}".format(feature_names[:100])) 
print("Features 20080 to 20090:\n{}".format(feature_names[20080:20090]))

Number of features: 21637
First 100 features:
['00', '000', '0000', '007npen6lg', '00cy9vxeff', '00end', '00pm', '01', '02', '0215', '02elqlopfk', '02pm', '03', '030', '033', '034', '039', '03l7nwqdje', '04', '05', '05th', '06', '060', '061', '06jst', '07', '073izwx0lb', '08', '0840728', '0853', '087809233445', '0880', '08lngclzsj', '09', '0abgfglh7x', '0ajisa5531', '0blkwcupzq', '0btniwagt1', '0bvk5tub4j', '0c1y8g7e9p', '0cr74m1uxm', '0cxm5tkz8y', '0dqjeretxu', '0drqlrsgy5', '0dxvz7fdh3', '0erisq25kt', '0f8xa4ih1u', '0fekgyby5f', '0fs9ksv5xk', '0ghk693egj', '0gidg9u45j', '0gknpy4lua', '0h7oua1pns', '0iw6drf5x9', '0iyuntxduv', '0jfnvaxfph', '0jmkdtcymj', '0kccg1bt06', '0keh2treny', '0krw1zyahm', '0l', '0la1aw9uud', '0llwuqn8vg', '0lmheaex9k', '0lpu0gr2j0', '0m1tw3datd', '0mcxc68gzd', '0migwcmtje', '0mnpcer9no', '0npzp', '0nr4dpjgyl', '0oms8ri3l1', '0pamznyyuw', '0q040stkcv', '0r03c6njli', '0rny349unt', '0rokdutyun', '0rsverlztm', '0s6ydfrwdq', '0sa6xx1oq7', '0scnwe8xbv', '0szwlwl9qu', 

In [6]:
X.shape

(7613, 21637)

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV


In [8]:
scores = cross_val_score(LogisticRegression(max_iter=10000), X, y, cv=5) 
print("Mean cross-validation accuracy: {:.2f}".format(np.mean(scores)))

Mean cross-validation accuracy: 0.71


In [9]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10,100]}
grid = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5) 
grid.fit(X,y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)

Best cross-validation score: 0.73
Best parameters:  {'C': 0.1}


In [10]:
# Let's remove noise first, by removing all elements that appear less than 5 times

vect = CountVectorizer(min_df=5).fit(data) 
X1 = vect.transform(data)
X1

feature_names = vect.get_feature_names()
print("Number of features: {}".format(len(feature_names)))
print("First 100 features:\n{}".format(feature_names[:100]))
print("Features 2000 to 2020:\n{}".format(feature_names[2000:2020]))

Number of features: 2795
First 100 features:
['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '100', '101', '10th', '11', '12', '12000', '13', '130', '14', '15', '150', '16', '16yr', '17', '18', '19', '1945', '1980', '1st', '20', '2011', '2013', '2014', '2015', '21', '22', '23', '24', '25', '26', '27', '29', '2nd', '30', '300', '300w', '30pm', '31', '32', '320', '33', '35', '36', '3g', '40', '4000', '43', '45', '48', '495', '4wd', '4x4', '50', '500', '53inch', '5km', '5th', '60', '600', '70', '70th', '731', '75', '77', '90', '94', '95', '97', '99', 'aba', 'abandoned', 'abc', 'abcnews', 'ablaze', 'able', 'about', 'above', 'absolutely', 'abstorm', 'abuse', 'access', 'accident', 'accidentally', 'accidents', 'according', 'account', 'acres', 'across', 'act']
Features 2000 to 2020:
['reporting', 'reports', 'republican', 'republicans', 'rescue', 'rescued', 'rescuers', 'research', 'residential', 'residents', 'resistant', 'respect', 'respond', 'responders', 'responds', 'respon

In [11]:
# after df=5 , let's see the results
scores = cross_val_score(LogisticRegression(max_iter=10000), X1, y, cv=5) 
print("Mean cross-validation accuracy: {:.2f}".format(np.mean(scores)))

Mean cross-validation accuracy: 0.70


In [12]:
# How about grid search for parameter C
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10,100]}
grid = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5) 
grid.fit(X1,y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)

Best cross-validation score: 0.73
Best parameters:  {'C': 0.1}


In [13]:
# So cleaning noise hasn't improved accuracy
# how about tfid ?

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(TfidfVectorizer(min_df=5, norm=None),LogisticRegression(max_iter=10000))
param_grid = {'logisticregression__C': [0.001, 0.01, 0.1, 1, 10]}
grid = GridSearchCV(pipe, param_grid, cv=5)
grid.fit(data,y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))


Best cross-validation score: 0.73


In [15]:
# no difference after tfid
# how about n-gram?



In [16]:
vect = CountVectorizer(min_df=5,ngram_range=(1, 3)).fit(data) 
X1 = vect.transform(data)
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10,100]}
grid = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5) 
grid.fit(X1,y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)



Best cross-validation score: 0.73
Best parameters:  {'C': 0.1}


In [17]:
# so no change, after n-gram maximum accuracy is 0.73
# how about english-stopwords?
vect = CountVectorizer(min_df=5, stop_words="english").fit(data)
X1 = vect.transform(data)
grid = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5) 
grid.fit(X1,y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)


Best cross-validation score: 0.71
Best parameters:  {'C': 0.1}


In [18]:
# accuracy decreases after using stopwords

In [19]:
# So every method to improve accuracy fails here 


In [20]:
# Let's try on unseen test data 
# Model for evaluation
logreg=LogisticRegression(C=0.1,max_iter=10000)
vect = CountVectorizer(min_df=5)
vect.fit(data)
X = vect.transform(data)
logreg.fit(X,y)

LogisticRegression(C=0.1, max_iter=10000)

In [21]:
# Let's get all the training and test data together , but won't that be leakage?
# Ok, still let's give it a try


In [22]:
a1=pd.read_csv(r"/Users/vijay/Downloads/nlp-getting-started/train.csv")
a2=pd.read_csv(r"/Users/vijay/Downloads/nlp-getting-started/test.csv")
a1_data=np.array(a1)
a2_data=np.array(a2)
a1_target=y

In [23]:
a1_target.shape

(7613,)

In [24]:
a1_data[:,3].shape

(7613,)

In [25]:
a2_data[:,3].shape

(3263,)

In [26]:
total_data=np.hstack([a1_data[:,3],a2_data[:,3]])
total_data.shape

(10876,)

In [27]:
vect = CountVectorizer(min_df=5,ngram_range=(1, 2))
vect.fit(total_data)
total_X = vect.transform(total_data)
total_X.shape


(10876, 7390)

In [28]:
total_X[0:7613,:]

<7613x7390 sparse matrix of type '<class 'numpy.int64'>'
	with 123842 stored elements in Compressed Sparse Row format>

In [29]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(max_iter=10000), param_grid, cv=5) 
grid.fit(total_X[0:7613,:],y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)

Best cross-validation score: 0.73
Best parameters:  {'C': 0.1}


In [30]:
logreg=LogisticRegression(C=0.1,max_iter=10000)
logreg.fit(total_X[0:7613,:],y)
prediction=logreg.predict(total_X[7613:10876,:])
prediction

array([0, 0, 1, ..., 1, 1, 0])

In [31]:
id=np.array(a2)[:,0].reshape(-1,1)
id

array([[0],
       [2],
       [3],
       ...,
       [10868],
       [10874],
       [10875]], dtype=object)

In [32]:
result=np.hstack([id,prediction.reshape(-1,1)])
dict = {'id': result[:,0], 'target': result[:,1]} 
df = pd.DataFrame(dict,index=None)
df.to_csv(r"/Users/vijay/Downloads/nlp-getting-started/result_nlp.csv",index=False)

In [33]:
# Another try using f1 score

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import f1_score

X_train, X_test, y_train, y_test = tts(total_X[0:7613,:],y,stratify=y, random_state=26)

logreg = LogisticRegression(max_iter=10000,C=0.1,random_state=12)
logreg.fit(X_train,y_train)
pl=logreg.predict(X_test)
 
confusion = confusion_matrix(y_test, pl) 

f1=f1_score(y_test, pl)

print('f1_score:',f1)
print('confusion:', confusion)

print('accuracy_train',logreg.score(X_train,y_train))
print('accuracy_test',logreg.score(X_test,y_test))



f1_score: 0.7508350033400133
confusion: [[969 117]
 [256 562]]
accuracy_train 0.8637239446488001
accuracy_test 0.8040966386554622


In [34]:
# for low values of C , f_score is poor
# for high values of C model is overfit


In [35]:
# C betwwen range of 0.1 to 1 is good



In [36]:
# End of project , If you have other methods let's see


In [37]:
# How about applying SVC

In [38]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100],
                  'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}
print("Parameter grid:\n{}".format(param_grid))

Parameter grid:
{'C': [0.001, 0.01, 0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}


In [39]:
from sklearn.svm import SVC
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid.fit(total_X[0:7613,:],y)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))
print("Best parameters: ", grid.best_params_)


Best cross-validation score: 0.73
Best parameters:  {'C': 1, 'gamma': 0.01}
